name: Erlang CI

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        erlang: [ 24,25 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v2
    - run: ./rebar3 compile

  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        erlang: [ 24,25 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v2
    - run: ./rebar3 compile
    - name: Unit Tests
      run: ./rebar3 eunit
    - name: Property-based Tests
      run: ./rebar3 proper -n 250

